### ISSUE TITLE
Investigate why gh-action occasionally fails on each project

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides-stats#3] opened 2022-03-16 13:09 UTC
Noticed that the github actions occasionally fails without providing any reason, but then recovers the next day. This doesn't seem to be specific to a particular project or a particular day. We just want to get ahead of this in case it causes problems or gaps in our data history. 

Some history of failed runs:
* March 4: fetch-all-fides-stats / fetch-all-fides-stats (ethyca/fideslang) Failed in 43 seconds
* March 6: fetch-all-fides-stats / fetch-all-fides-stats (ethyca/fides) Failed in 48 seconds
* March 9: fetch-all-fides-stats / fetch-all-fides-stats (ethyca/fidesops) Failed in 41 seconds
* March 13: fetch-all-fides-stats / fetch-all-fides-stats (ethyca/fideslang) Failed in 40 seconds

On March 7, I did replace the token to just make sure it wasn't something silly like that, but that's the only "troubleshooting" I've tried to date.

**Comment by ThomasLaPiana** [comment] 2022-03-22 15:06
I could add some retry logic I think, so it'll try the job a few times if it fails. maybe that'd be enough to get over the inconsistency?

**Comment by iamkelllly** [comment] 2022-03-22 23:48
I'm not claiming to be an expert, but relying on Github Actions to reliably pull data on the daily from 3 repos (and growing, we're going to want to add our other projects to this later) doesn't seem like the best idea. Also, gh actions has been having pretty frequent incidents in the last couple weeks right? Is there something else we can use to pull the data from these repos directly? As I'd mentioned before, if we only use this repo to backfill snowflake, that's totally fine. If we can come up with a more reliable solution, I'd be completely okay with deleting this project as a whole.

**Comment by ThomasLaPiana** [comment] 2022-03-24 19:47
we'd be venturing into doing some proper data engineering, which is doable but takes resources, would also need monitoring, etc. could use something like Meltano as they might have a github connector.

The jump in scope is pretty large, so I think how important this data/what our data loss tolerance is will inform how much we invest in getting these pipelines setup.

Additionally, despite that stuff failing it looks like there aren't any gaps in data? since it goes back 14 days, it seems like as long as it doesn't fail for 14 days its able to attribute that data properly, but maybe I'm wrong there

**Comment by sanders41** [comment] 2022-04-03 14:24
The failure always looks to be `github.GithubException.GithubException: 500 null`. The `github-repo-stats` action has a built in retry mechanism, but the [conditions that trigger the retry](https://github.com/jgehrcke/github-repo-stats/blob/074445ed37842074a09253bb2d638b96a613cf5d/fetch.py#L433) do not include this exception.

Based on the [GitHub status history](https://www.githubstatus.com/history) the failures don't seem to be strongly correlated to all the issues with GitHub going down lately.

Maybe there is a way to add a custom retry on an `github.GithubException.GithubException: 500 null` exception and that might help?

**Comment by iamkelllly** [comment] 2022-04-07 12:15
Thank you for this suggestion @sanders41 ! I think we will explore adding a custom retry for the action, but look at a longer term solution in parallel.

For this week's serial error, we saw authentication failures, so I've regenerated the token for another 90d token for this to rule that out.

**Comment by sanders41** [comment] 2022-04-07 12:22
In the meantime I have tried recreating this error outside of GitHub Actions on some of my repositories and have not seen the error yet. I was hoping to find a pattern, but so far the only thing that seems to be consistent is when it is run as an Action. Unfortunately since it is random even when running in Actions I can't say for sure that is the root cause.

**Comment by iamkelllly** [comment] 2022-04-22 16:57
Bumping this again @ThomasLaPiana It's now been over a month and there are gaps in our data. Can we please investigate a fix?

**Comment by ThomasLaPiana** [comment] 2022-04-25 01:26
@iamkelllly I would bet some money that its this line: https://github.com/ethyca/fides-stats/blob/main/.github/workflows/fetch-all-fides-stats.yml#L32

Where did you generate/get this token from?

**Comment by iamkelllly** [comment] 2022-04-25 02:11
I generated the token from my gh account and store it in the repo secrets vault. I can show you how tomorrow? Or if that is incorrect, then how can we generate it properly?

**Comment by ThomasLaPiana** [comment] 2022-04-25 13:55
I believe GitHub CI runners are automatically supplied with a token for gitops, and all of those repos are public anyway right? I'll dig more into this but that's the only place I can think the issue would be

**Comment by ThomasLaPiana** [comment] 2022-04-25 13:58
installation instructions suggest a personal token 🤔 
https://github.com/jstrieb/github-stats#installation

**Comment by ThomasLaPiana** [comment] 2022-04-25 14:53
@iamkelllly I generated a new personal access token using the guide in fides-stats, and I set the expiry to `never`. Updated the secret in this repo and everything looks good 🤷 

https://github.com/ethyca/fides-stats/actions/runs/2217110142

**Comment by iamkelllly** [comment] 2022-04-25 15:08
Okay it will definitely be something to watch, I followed the same instructions and it stopped working after 6-7 weeks the first time, and apparently pressing "regenerate token" for the same token that was originally created never worked again.

**Comment by ThomasLaPiana** [comment] 2022-04-25 15:40
ok, i'll close this but keep an eye on it

**Closed as completed by ThomasLaPiana** 2022-04-25 15:40 UTC
Labels: bug
